### ISSUE TITLE
Improper quoting in first 100 rows on EVENTS

### ISSUE THREAD

**Issue by t-andresvaz** [UMC-Utrecht-RWE/ConcePTION-Level1#2]
Message from [aemps.es]

We have already executed the level 1 check script but we have an issue in events.

Quitting from lines 899-900 (Step4to5-EVENTS.v12.13_05_2021.Rmd)
Error in fread(paste0(tmp, dup_files[i]), sep = ";") :
  R character strings are limited to 2^31-1 bytes
In addition: Warning messages:
1: In fread(paste0(tmp, dup_files[i]), sep = ";") :
  **Found and resolved improper quoting in first 100 rows. If the fields are not quoted (e.g. field separator does not appear within any field), try quote="" to avoid this warning.**

**Comment by t-andresvaz** [comment]
Review if your file is indeed extracted using , or ; as separator and ` or "  to quote text variables. The next step is to understand with you have any of this chars inside the values (this is going to rise this warning message also). The solution is to clean the extraction as previously mentioned (REPLACE) text variables in the SELECT clause of the query. If nothing of this works, the next step is to truncate the text variables with TRUNC(variable, 2000) to limit the size of the text. Modern computers have a limit to deal with large text inside CSV files, so truncating the value may be useful.

**Comment by acidroyo-UMCU** [comment]
I suggest testing the 100 first lines of the already generated .csv files with the following commands:
fread(filesName.csv, sep = ";",nrows=100) 
fread(filesName.csv, nrows=100) 

And compare the results. fread will try to find the best parser for your .csv file.

**Comment by anallg** [comment]
You can close this one. We have removed all the free text in event files. We have an other problem but I´ll tell you in other "issue"
