### ISSUE TITLE
link to L1b checks

### ISSUE THREAD

**Issue by hainguyent** [UMC-Utrecht-RWE/ConcePTION-Level1#6]
Hi, 

We were sent these instructions for level 1b checks: 
https://vac4eu.sharepoint.com/:w:/r/sites/Toolbox/_layouts/15/Doc.aspx?sourcedoc=%7B3EA195E8-DCA5-48BB-9210-0E2B40ABC1A6%7D&file=VAC4EU%20Level%201b%20checks%20instructions%20AllStudies%20Jun20221.docx&action=default&mobileredirect=true
However, when I clicked on the 'releases' hyperlink, it takes me to Level 2 releases. Can you please send me the correct link for level 1b checks?

Many thanks,

Hai

**Comment by t-andresvaz** [comment]
Here is the link for the Level 1b:

[Level 1b release](https://github.com/UMC-Utrecht-RWE/ConcePTION-Level1b/releases/tag/v1.1
)
documentation is now fixed.
