### ISSUE TITLE
Run out of RAM

### ISSUE THREAD

**Issue by frasansa** [UMC-Utrecht-RWE/ConcePTION-Level1#9]
Dear @t-andresvaz @relbersumcu,

We are doing the QC for VID datasource for consign and we have some issues with the RAM that are causing:

- In _**level 1 check**_ the EVENTS folder is empty. 
- In **_level 2 check_** the MEDICINES and VACCINES are unable to perform check in most of the reports.

There are some strategy to follow for fixing this (splitting some tables by year or similar)?
Thank you in advance,
Francisco

**Comment by frasansa** [comment]
@t-andresvaz 
Do you have any idea?
Thanks.

**Comment by t-andresvaz** [comment]
Can you meet tomorrow morning to inspect outputs together?

**Comment by frasansa** [comment]
Thanks Tiago,

With your answer in the other repo issue we are performing the QC. The level 1b outputs are already uploaded in mydre. We will upload the rest of QC when they finish. I close the issue.
